/*Copyright (c) 2011-2016 Moat Inc. All Rights Reserved.*/
try{(function(x,t){var v={},A=[],u={},B=[],y={};v.a=function(){for(var a=0;a<A.length;a++)window.clearTimeout(A[a]);for(a=0;a<B.length;a++)window.clearInterval(B[a]);for(var e in u)u.hasOwnProperty&&u.hasOwnProperty(e)&&u[e]&&(window.clearTimeout(u[e].tid),u[e]=!1);A=[];B=[]};(function(a){function e(a){var k=new RegExp("(^| )"+a+"($| )");return function(a){return a&&a.className&&a.className.match(k)}}function b(a){return a&&a.document&&a.location&&a[l+q]&&a[c+r]}function d(a){if(null==a||b(a))return!1;
var k=a.length;return 1===a.nodeType&&k?!0:"string"===typeof a||m(a)||0===k||"number"===typeof k&&0<k&&k-1 in a}function m(f){return"[object Array]"===a.b.be.toString.call(f)}a.b={};a.b.a=3E3;a.b.b=function(){var a=/Firefox\/(\d+)/.exec(navigator.userAgent);return a?(a=parseInt(a[1],10),21>a&&14<a):!1}();a.b.c=function(){var f,k=/^(?:[a-z]+:\/\/|:?\/?\/)?(?:www\.)?([^\/:]*)/i;a.c.a||(f=a.b.d(),!f&&a.c.b&&(f=a.c.b));f||(f=a.c.c.location.hostname);return(f=f&&f.match&&f.match(k))&&f[1]||a.c.c.location.hostname};
a.b.d=function(){var a=location&&location.ancestorOrigins;return a?0===a.length?!1:a[a.length-1]:!1};a.b.e=function(){var f,k=a.b.c(),n=k&&k.split("."),c=n&&n.length;3<=c?f="co"===n[c-2]||"com"===n[c-2]?n[c-3]+"."+n[c-2]+"."+n[c-1]:n[c-2]+"."+n[c-1]:2==c&&(f=n[c-2]+"."+n[c-1]);return f&&decodeURIComponent(f)||decodeURIComponent(k)};a.b.f=function(a){if("string"!==typeof a)return"";var k=a.match(/^([^:]{2,}:\/\/[^\/]*)/);k&&k[1]&&(a=k[1]);return a};a.b.g=function(a,k){for(var n=[a],c=1;c<=k;c++)n.push(a+
c),n.push(a-c);n=n[t.floor(t.random()*n.length)];c=t.floor(t.random()*n);return{multiplier:n,sample:0==c}};a.b.h=function(f,k){var n=a.b.g(f,k);a.b.h=function(){return n};return n};a.b.i=function(){var f=!0;return f=a.b.h(32,2).sample};a.b.j=function(){var f=a.b.k();return 5===f||6===f||7===f};a.b.k=function(){if(!navigator)return null;var a;a=navigator.userAgent;return"Microsoft Internet Explorer"==navigator.appName?parseInt(a.replace(/^.*MSIE (\d+).*$/,"$1"),10):"Netscape"==navigator.appName&&(a=
a.match(/(?:Trident\/.*rv:|MSIE )(\d+)/))?parseInt(a[1],10):null};a.b.l=function(){return null!=a.b.k()};a.b.m=function(f,k){return-1!==a.b.indexOf(f,k)};a.b.getElementsByClassName=function(a,k,n){k=k||"*";n=n||document;if(n.getElementsByClassName){var c=[],b=n.getElementsByClassName(a);if("*"!==k){a=0;for(n=b.length;a<n;a++){var g=b[a];g.tagName===k&&c.push(g)}return c}return b}b=[];k=n.getElementsByTagName(k);n=e(a);g=k.length;for(a=0;a<g;a++)c=k[a],n(c)&&b.push(c);return b};a.b.n=e;a.b.o=function(a){return new x-
a.de};a.b.p=function(a){return a.replace(/^http:/,"").replace(/^\/\//,"").replace(/^www[^.]*\./,"").split("/")[0]};a.b.q=function(f,k,n){if(("undefined"===typeof n||!n)&&f&&(n=a.b.r(f),!n))return;if(f&&f.nodeType)if("undefined"===typeof Node){if(1!=f.nodeType)return}else if(f.nodeType!=Node.ELEMENT_NODE)return;if(n.getComputedStyle)return n.getComputedStyle(f,"")&&n.getComputedStyle(f,"")[k];for(n=k.indexOf("-");-1<n;)k=n==k.length-1?k.substr(0,n):k.substr(0,n)+k.charAt(n+1).toUpperCase()+k.substr(n+
2),n=k.indexOf("-");if(f.currentStyle)return f.currentStyle[k];if(f.style)return f.style[k]};a.b.s=function(f){if(!f)return!1;var k=a.b.q(f,"background-image");k||(k=a.b.q(f,"backgroundImage"));var n;k&&(n=(n=k.match("url\\((.*)\\)"))&&n[1].replace(/\x22/g,""));return n};a.b.t=function(f,k){if(!f)return!1;var n=[f],c=!1;a.b.forEach("number"===typeof k?k:50,function(){if((c=a.b.u(f))&&1==c.nodeType)f=c,n.push(f);else return!1});return n};a.b.u=function(a){return a.parentNode||a.parentElement||!1};
a.b.v=function(f,k){var c="number"===typeof k?k:50,b=[],g=a.b.r(f);if(g)b.push(g);else return b;a.b.forEach(c,function(){var k=a.d.a(f,g);return k&&(g=a.b.r(k))?(b.push(g),!0):!1});return b};a.b.w=function(){return null!==/iPad|iPhone|iPod|Silk|Kindle|Android|BlackBerry|PlayBook|BB10|Windows Phone|SpreadTrum|MAUI/.exec(navigator&&navigator.userAgent||"")};a.b.x=function(){return null!==/iPhone|iPod/.exec(navigator.userAgent)};a.b.y=function(){return null!==/iPad/.exec(navigator.userAgent)};a.b.z=
function(){return null!==/Android/.exec(navigator.userAgent)};a.b.aa=function(){var a=navigator.userAgent;return a.match(/iPhone|iPod|iPad/)&&!a.match(/Safari|CriOS/i)};a.b.ab=function(){var f=navigator.userAgent;return a.b.z()&&f.match(/Version/)};a.b.ac=function(){var f;return function(){if("undefined"!==typeof f)return f;f={isInApp:0,env:"Not app"};a.b.aa()?(f.isInApp=1,f.env="iOS"):a.b.ab()&&(f.isInApp=1,f.env="Android");return f}}();a.b.ad=function(){var f=a.b.ac(),k=a.c.c.screen;if("iOS"===
f.env)return"undefined"!==typeof window.orientation?0===window.orientation||180===window.orientation?(f=k.width,k=k.height):(f=k.height,k=k.width):f=k=0,{w:f,h:k};if("Android"===f.env){var f=a.c.c.devicePixelRatio,c=1;.05>t.abs(k.width/a.c.c.innerWidth-f)&&(c=f);return{w:k.width/c,h:k.height/c}}return{w:k.width,h:k.height}};a.b.ae=function(){return a.b.af()?a.b.ag()?1:2:0};a.b.af=function(){var f;return function(){if("undefined"!==typeof f)return f;var k=a.c.c,c=a.b.ad();if(a.c.c.navigator.standalone)f=
!0;else{var b=k.innerWidth/c.w,k=k.innerHeight/c.h,b=!isNaN(b)&&isFinite(b)&&.9<=b&&1.1>=b,k=!isNaN(k)&&isFinite(k)&&.75<=k&&1.1>=k;f=b&&k}return f}}();a.b.ag=function(){var f=a.b.af(),k=a.b.e(),c=a.c.d(),b="applewebdata:"===window.location.protocol||"data:"===window.location.protocol,k="-"===k||""===k.replace(/^\s+|\s+$/gm,"");return f&&!(k||c||b)};a.b.ah=function(){return function(){}}();a.b.ai=function(){return a.b.ah()?!!document.getElementById(APPSCOPE_CONTAINER_ID):!1};a.b.aj=function(){var f;
return function(){return"undefined"!==typeof f?f:f=a.b.af()}}();a.b.ak=function(){var a=window;try{return"undefined"!==typeof a.external&&"undefined"!==typeof a.external.InPrivateFilteringEnabled&&a.external.InPrivateFilteringEnabled()||"undefined"!==typeof a.external&&"undefined"!==typeof a.external.msTrackingProtectionEnabled&&a.external.msTrackingProtectionEnabled()||"undefined"!==typeof a._gaUserPrefs&&a._gaUserPrefs.ioo&&a._gaUserPrefs.ioo()||"undefined"!==typeof navigator.doNotTrack&&("yes"===
navigator.doNotTrack||!0===navigator.doNotTrack)||"undefined"!==typeof a._gaUserPrefs&&!0===a._gaUserPrefs}catch(k){return!1}};a.b.al=function(){return!1};a.b.getAttribute=function(a,k){return a[k]||a.getAttribute(k)};a.b.am=function(a){var k=0,c;for(c in a)a.hasOwnProperty(c)&&(k+=1);return k};var h=[function(a){if(!a||"IFRAME"!==a.nodeName)return!1;var k=a.offsetHeight;return isNaN(k)||15<k||"google_conversion_frame"!==a.name?!1:!0}];a.b.an=function(f,k){return"undefined"===typeof f||null===f||
!1===f||!a.b.ao(f)||f.nodeName&&"IMG"==f.nodeName&&!f.complete||a.b.filter(h,function(a){return a(f)}).length||!0===f[MOATALREADYFOUND]?!1:!0};a.b.ap=function(a){return a.replace(/:/g,"%3A").replace(/=/g,"%3D").replace(/,/g,"%2C")};a.b.aq=function(f){var k=[];a.b.forEach(f,function(f,c){var b=typeof f;"number"==b?k.push(a.b.ap(c)+":"+a.b.ap(f+"")):"string"==b?k.push(a.b.ap(c)+":"+a.b.ap('"'+f+'"')):"undefined"==b?k.push(a.b.ap(c)+":"+a.b.ap("undefined")):"boolean"==b?k.push(a.b.ap(c)+":"+a.b.ap(f?
"true":"false")):null===f?k.push(a.b.ap(c)+":"+a.b.ap("null")):"object"!=b&&"function"!=b||!f.toString||k.push(a.b.ap(c)+":"+a.b.ap('"'+f.toString()+'"'))},null,!0);k.sort();return"{"+k.join(",")+"}"};a.b.ar=function(a){var k={};if("string"!=typeof a||"{"!=a[0])return!1;a=a.slice(1,-1).split(",");for(var c=0;c<a.length;c++){var b=a[c].split(":");b[1]=unescape(b[1]);b[1]="true"==b[1]?!0:"false"==b[1]?!1:'"'==b[1][0]?b[1].slice(1,-1):"undefined"==b[1]?void 0:"null"==b[1]?null:"NaN"==b[1]?NaN:parseFloat(b[1]);
k[unescape(b[0])]=b[1]}return k};a.b.ao=function(f){var k=f.offsetWidth,c=f.offsetHeight;a.b.forEach(a.b.t(f,3),function(a){if(a&&a.style&&(""!=a.style.width||""!=a.style.height)&&"hidden"==a.style.overflow){var f=parseFloat(a.style.width);a=parseFloat(a.style.height);k=!isNaN(f)&&f<k?f:k;c=!isNaN(a)&&a<c?a:c}});if(f=a.b.as(f))k=f.width<k?f.width:k,c=f.height<c?f.height:c;return k*c>=a.b.a};var p={};a.b.as=function(f){if(!(f&&f.src&&f.nodeName&&"IMG"!=!f.nodeName&&f.complete))return!1;if(p[f.src])return p[f.src];
try{if("undefined"!==typeof f.naturalHeight&&"undefined"!==typeof f.naturalWidth){var c={width:f.naturalWidth,height:f.naturalHeight};return p[f.src]=c}}catch(b){}return a.c.e&&(a.c.e.src=f.src,a.c.e.a)?(c={width:parseInt(a.c.e.b),height:parseInt(a.c.e.c)},p[f.src]=c):!1};a.b.at=function(){var a;return function(){if(!a)a:{for(var c=document.getElementsByTagName("script"),b=c.length-1;-1<b;b--)if((a=c[b])&&a.src&&a.src.indexOf&&(-1!==a.src.indexOf("redditadzerk107343723525/moatad.js")||-1!==a.src.indexOf("redditadzerk107343723525%2Fmoatad.js"))&&
("undefined"===typeof a[MOATALREADYFOUND]||!0!==a[MOATALREADYFOUND])){a[MOATALREADYFOUND]=!0;break a}a=void 0}return a?(a[MOATALREADYFOUND]=!0,a):null}}();a.b.au=function(a){for(var c=[],b=a&&a.getElementsByTagName("script"),g=b.length-1;-1<g;g--)(a=b[g])&&a.src&&a.src.match(/moatads.com\/.*\/moat(ad|video)\.js/)&&!a.src.match("redditadzerk107343723525")&&c.push(a);if(c&&0<c.length)return c};a.b.av=function(f,c){if(!f||!c)return!1;var b=a.b.au(a.c.f?thisScript.ownerDocument.body||c:c);if(b&&0<b.length){var g=
b[0]&&b[0].src&&b[0].src.match(/moatads.com\/(.*)\/moat(ad|video)\.js/);g&&g[1]&&(f.zMoatOtherScript=g[1],(b=a.e.a(b[0]))?(b=b.cleanMoatClientLevel1+":"+b.cleanMoatClientLevel2+":"+b.cleanMoatClientLevel3+":"+b.cleanMoatClientLevel4,f.zMoatOtherHash=b?b:"IDs Not Available"):f.zMoatOtherHash="IDs Not Available")}};a.b.aw=function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};a.b.ax=function(a,c){if("string"!==typeof a||!c||!c.insertBefore||!c.ownerDocument)return!1;var b=c.ownerDocument.createElement("script");
b.type="text/javascript";b.async=!0;c.insertBefore(b,c.childNodes[0]);b.src=a;return!0};a.b.ay=function(a){var c;if(a)c=/https:/i.test(a.src||a.href||"http:")?"https:":"http:";else try{c=window.location.protocol}catch(b){a=document.createElement("a"),a.href="",c=a.protocol}return"https:"===c?"https:":"http:"};a.b.az=function(a){try{return-1!==(a.src||a.getAttribute("src")).indexOf("psd=1")}catch(c){return!1}};a.b.ba=function(a){for(var c=[],b=0;b<a.length;b++)c.push(a[b]);return c};a.b.nextElementSibling=
function(a){if(a.nextElementSibling)return a.nextElementSibling;for(;a=a.nextSibling;)if(1===a.nodeType)return a};a.b.previousElementSibling=function(a){if(a){if(a.previousElementSibling)return a.previousElementSibling;for(var c=0;(a=a.previousSibling)&&1E3>c;)if(c++,a&&1===a.nodeType)return a}};a.b.bb=function(a,c,b){"undefined"!==typeof b&&(a[c]=b)};a.b.filter=function(a,c){for(var b=[],g=0;g<a.length;g++)c(a[g])&&b.push(a[g]);return b};a.b.bc=function(a,c){for(var b=[],g=0;g<c.length;g++)b.push(a(c[g]));
return b};a.b.indexOf=function(f,c){if(!f)return-1;if(a.b.bd(f)){for(var b=0,g=f.length;b<g;b++)if(f[b]===c)return b;return-1}return"string"===typeof f?f.indexOf(c):-1};a.b.bind=function(a,c){return function(){a[c].apply(a,arguments)}};var l="ale",q="rt",c="setInte",r="rval";a.b.be={};a.b.bf=function(a,c){if(a&&c&&c.childNodes){var b=c.childNodes;0<b.length?c.insertBefore(a,b[0]):c.appendChild(a)}};a.b.bg=function(c,b){if(!c||!b)return!1;var g=a.b.bh(b);if(!g)return!1;if(a.b.hasChildNodes(g)){var d=
g.childNodes[t.max(0,g.childNodes.length-1)]||null;g.insertBefore(c,d)}else g.appendChild(c);return g};a.b.bi=function(c,b,g){if("string"!=typeof c||!b||!document)return!1;g=g||document.createElement("script");g.type="text/javascript";b=a.b.bg(g,b);if(!b)return!1;g.src=c;return b};a.b.hasChildNodes=function(a){return a&&a.childNodes&&0<a.childNodes.length};a.b.bh=function(c){if(!c)return!1;if("OBJECT"!==c.nodeName&&"EMBED"!==c.nodeName)return c;c=a.b.t(c);var b=!1;a.b.forEach(c,function(a){if(a&&
"OBJECT"!==a.nodeName&&"EMBED"!==a.nodeName)return b=a,!1});return b};a.b.bj=function(a,c){if("undefined"===typeof a)return!1;for(var b=0,g=c.length;b<g;b++)if("string"==typeof c[b]){try{a=a[c[b]]}catch(d){}if("undefined"===typeof a)return!1}return a};a.b.bk=function(a){return encodeURIComponent(a.moatClientLevel1+":"+a.moatClientLevel2+":"+a.moatClientLevel3+":"+a.moatClientLevel4)};a.b.bl=function(a){return y&&"undefined"!==typeof a&&y[a]?y[a]:!1};a.b.bm=function(a){return a&&"function"===typeof a?
0>String(Function.prototype.toString).indexOf("[native code]")?a===Function.prototype.toString?!1:null:0<=String(a).indexOf("[native code]")&&!0||!1:!1};a.b.bd=m;a.b.bn=b;a.b.bo=d;a.b.forEach=function(a,c,b,g){var l,r=typeof a;if(a)if("function"===r)for(l in a){if("prototype"!=l&&"length"!=l&&"name"!=l&&(g||!a.hasOwnProperty||a.hasOwnProperty(l))&&(r=c.call(b,a[l],l),"boolean"===typeof r&&!r))break}else if("number"===r)for(l=0;l<a&&(r=c.call(b,a,l),"boolean"!==typeof r||r);l++);else if("function"===
typeof a.every)a.every(function(a,f,g){a=c.call(b,a,f);return!("boolean"===typeof a&&!a)});else if(d(a))for(l=0;l<a.length&&(r=c.call(b,a[l],l),"boolean"!==typeof r||r);l++);else for(l in a)if(g||a.hasOwnProperty(l))if(r=c.call(b,a[l],l),"boolean"===typeof r&&!r)break;return a};a.b.bp=function(c){return c&&a.b.filter(c.children,function(a){return 1===a.nodeType})};a.b.bq=function(a){if(!a||!a.aa)return!1;if("number"!=typeof a.ADAREA){var c,b;a.elementRect?(c=a.elementRect.right-a.elementRect.left,
b=a.elementRect.bottom-a.elementRect.top):(c=a.aa.offsetWidth,b=a.aa.offsetHeight);a.ADAREA=c*b}return a.ADAREA};var g=/rect\((\d+)px,? ?(\d+)px,? ?(\d+)px,? ?(\d+)px\)/;a.b.br=function(c){c=c.match(g);var b=!1;c&&(c=a.b.bc(function(a){return parseInt(a,10)},c),b={top:c[1],right:c[2],bottom:c[3],left:c[4]});return b};a.b.bs=function(c){if(!c)return!1;var b=!1;if(c!==Object(c))b=c;else if(a.b.bo(c))for(var b=[],g=0,d=c.length;g<d;g++)b[g]=c[g];else for(g in b={},c)b[g]=c[g];return b};a.b.trim=function(a){return String.prototype.trim?
a.trim():a.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,"")};a.b.bt=function(){var a=function(){var a=window.pageXOffset?window.pageXOffset+window.innerWidth-1:0,c=window.pageYOffset?window.pageYOffset+window.innerHeight-1:0;return a||c?!document.elementFromPoint(a,c):!0}();return function(c,b,g){if(!a){var d=g.defaultView||g.parentWindow||window;c+=d.pageXOffset;b+=d.pageYOffset}return g.elementFromPoint(c,b)}}();a.b.bu=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};a.b.bv=function(c,
b){if(!c||!b||"object"!=typeof c||"object"!=typeof b)return!1;var g=!0;a.b.forEach(c,function(a,c){if("string"!=typeof a&&"number"!=typeof a)return!0;if(!b.hasOwnProperty(c)||b[c]!==a)return g=!1});a.b.forEach(b,function(a,b){if("string"!=typeof a&&"number"!=typeof a)return!0;if(!c.hasOwnProperty(b)||c[b]!==a)return g=!1});return g};a.b.bw=function(a,c,b){return function(){c.apply(b||null,a.concat(a.slice.call(arguments)))}};a.b.r=function(a){try{var c=a&&a.ownerDocument;return c&&(c.defaultView||
c.parentWindow)}catch(b){return!1}};a.b.bx=function(c,b){if(!c||!b)return!1;for(var g=[],d,l=0;50>l;l++)if(b!=b.parent){if(d=a.d.a(c,b))g.push(d);else break;b=b.parent;c=d}else break;return g};a.b.by=function(a){a=t.max(4,a);return((1+t.random())*t.pow(16,a)|0).toString(16).substring(0,a)};a.b.bz=function(){var c=a.b.by;return c(4)+"-"+c(4)+"-"+c(4)+"-"+c(4)};a.b.ca=function(a){window&&window.clearTimeout&&window.clearTimeout(a)};a.b.cb=function(a){window&&window.clearInterval&&window.clearInterval(a)};
var z=function(c,b){if(a.b.bm(b.toString))return b.toString();if(a.b.bm(c&&c.Function.prototype.toString))return b.toString=c.Function.prototype.toString,b.toString();var g=a.c.c!==c&&a.c.c&&a.c.c.Function.prototype.toString;if(a.b.bm(g))return b.toString=g,b.toString();if(a.c.g&&8>=a.b.k())return b.toString();var g=c||window,d=g.document.createElement("IFRAME");d.style.display="none";d.style.width="0px";d.style.height="0px";d.width="0";d.height="0";a.b.bg(d,g.document.documentElement);d.contentWindow&&
(b.toString=d.contentWindow.Function.prototype.toString);var l=b.toString();g.document.documentElement.removeChild(d);return l};a.b.toString=function(c,b){b=b||a.c.c;var g;try{g=z(b,c)}catch(d){g=c.toString()}return g};a.b.cc=function(c,b,g){c=a.b.toString(c,g);if(a.c.h())g.eval("("+c+")("+b+")");else if(g.Function)(new g.Function("("+c+")("+b+")"))();else{var d=g.document.createElement("script");d.type="text/javascript";d.text="("+c+")("+b+")";a.b.bg(d,g.document.body)}};a.b.cd=function(c){var b=
[];a.b.forEach(c,function(a,c){b.push(c)});return b}})(v);(function(a){a.d={};a.d.b=function(e){if(!e)return null;try{if(e.moatHostileIframe)return null;if(e.src&&e.src.slice&&"http"===e.src.slice(0,4)&&a.b.p(e.src)!=a.b.p(D.location.toString()))return e.moatHostileIframe=!0,null;var b=e&&(e.contentDocument||e.contentWindow&&e.contentWindow.document);if(b&&"string"===typeof b.location.toString())return b;e.moatHostileIframe=!0;return null}catch(d){return e.moatHostileIframe=!0,null}};a.d.a=function(e,
b){b=b||a.b.r(e);try{return b&&b.frameElement}catch(d){return!1}};a.d.c=function(e,b){var d;a.b.forEach(e.getElementsByTagName("iframe"),function(a){if(a&&a.contentWindow&&a.contentWindow==b)return d=a,!1});return d};a.d.d=function(e){if(e=a.d.a(e))try{return e.parentNode}catch(b){}return null};a.d.e=function(e,b){if(!e)return!1;var d=0,m=[];for(b=b||10;d<b;)if(d++,e=a.d.a(e))m.push(e);else return m};a.d.f=function(e,b){if(!e)return!1;var d=0,m=[e],h;for(b=b||10;d<b;){d++;try{if(e=(h=e.frameElement)&&
a.b.r(h),h&&e&&!a.d.g(e))m.push(e);else return m}catch(p){break}}return m};a.d.h=function(e,b,d){var m=[];e&&m.push(e);d=d||0;if(10<d||!e||!e.frames)return m;for(var h=0,p=e.frames.length;h<p;h++)try{b&&!a.d.i(e.frames[h])?m.push(e.frames[h]):m=m.concat(a.d.h(e.frames[h],b,d+1))}catch(l){break}return m};a.d.j=function(a,b){b="number"==typeof b&&0<b?b:15;var d=[],m;if(a){m=a.top;for(var h=0;h<b;h++)if((a=a.parent)&&a!=a.top)d.push(a);else break;d.push(m)}return d};a.d.k=[];a.d.i=function(e){for(var b,
d=0,m=a.d.k.length;d<m;d++)a.d.k[d].win==e&&(b=a.d.k[d]);if(!b){b={win:e,friendly:!1};try{e.document&&(b.friendly=!0)}catch(h){}}return b.friendly};a.d.l=function(e,b,d){e=a.d.f(e).pop();e=a.d.h(e,!0);for(var m=0,h=e.length;m<h;m++)if(e[m]==b){if(d&&b.parent&&a.d.g(b.parent))break;return!0}return!1};a.d.g=function(a){try{var b=typeof a.location.toString;if("undefined"===b||"unknown"===b)return!0;var d=typeof a.document;if("undefined"===d||"unknown"===d)return!0;var m=a.innerWidth||a.document.documentElement.clientWidth||
a.document.body.clientWidth||0;return"number"!==typeof(a.screenX||a.screenLeft||0)||"number"!==typeof m?!0:!1}catch(h){return!0}}})(v);(function(a){a.c={};a.c.i="21";a.c.j="MoatSuperV"+a.c.i;a.c.k=0;a.c.l=window&&window["Moat#G"+a.c.i]||{};window["Moat#G"+a.c.i]=a.c.l;a.c.l.a||(a.c.l.a=t.floor(t.random()*t.pow(10,12)));a.c.m=0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor");a.c.n=-1!==navigator.userAgent.toLowerCase().indexOf("firefox");a.c.g=a.b.l();a.c.o=(new x).getTime();
a.c.p=!!window.opera||0<=navigator.userAgent.indexOf(" OPR/");a.c.q=!0;a.c.r=!0;var e=function(){var b=function(c){if(a.b.bj(c,["mraid","isViewable"])&&(c=c.mraid.isViewable,"function"===typeof c))try{return isMraidViewable=c(),"undefined"!==typeof isMraidViewable}catch(b){}return!1},d=document,e=window,c=b(e);if(!c&&a.c.s)for(var r=0;20>r&&!c;r++){d=a.d.a(d.body);if(!1!==d&&!d)break;d=(e=a.b.r(d))&&e.document;c=c||b(e)}a.c.t=function(){return c&&e};a.c.d=function(){return c};a.c.u=function(){return!1};
(function(){if(a.c.d()){var c="___mraid_loop___"+(new x).getTime(),b=a.b.bj(a.c.t(),["mraid","isViewable"]);b&&a.f.a(function(){return b()?(a.c.u=function(){return!0},!1):!0},{},300,c)}})()};a.c.t=function(){e();return a.c.t()};a.c.d=function(){e();return a.c.d()};a.c.u=function(){e();return a.c.u()};var b=function(){var b=function(c){if(a.b.ac.isInApp)return!1;c=a.b.bj(c,["$sf"]);if(!c)return!1;var b=c.ext;c=b&&b.geom;var g=b&&b.inViewPercentage,d=[["exp","b","t","l","r"],"self b t l r h w xiv yiv".split(" ")],
l;if(b&&c&&g&&"function"===typeof c&&"function"===typeof g)try{c=c();if(!c)return!1;if(c.par)return!0;for(var b=0,r=d.length;b<r;b++){l=d[b][0];for(var g=1,e=d[b].length;g<e;g++)if("undefined"===typeof c[l][d[b][g]])return!1}return!0}catch(p){}return!1},d=window,e=document,c=b(d),r=!(!c&&!d.$sf);if(!c&&a.c.s)for(var g=0;20>g&&!c;g++){e=a.d.a(e.body);if(!1!==e&&!e)break;e=(d=a.b.r(e))&&d.document;c=c||b(d);r=r||c||d.$sf}a.c.v=function(){return c&&d};a.c.w=function(){return c};a.c.x=function(){return r}};
a.c.y=!1;a.c.v=function(){b();return a.c.v()};a.c.x=function(){b();return a.c.x()};a.c.w=function(){b();return a.c.w()};var d=function(){var b=function(c){return a.b.ac.isInApp?!1:a.b.bj(c,["context","observeIntersection"])?!0:!1},d=window,e=document,c=b(d),r=!(!c&&!d.context);if(!c&&a.c.s)for(var g=0;20>g&&!c;g++){e=a.d.a(e.body);if(!1!==e&&!e)break;e=(d=a.b.r(e))&&d.document;c=c||b(d);r=r||c||d.context}a.c.z=function(){return c&&d};a.c.aa=function(){return c};a.c.ab=function(){return r}};a.c.z=
function(){d();return a.c.z()};a.c.ab=function(){d();return a.c.ab()};a.c.aa=function(){d();return a.c.aa()};a.c.protocol=a.b.ay();a.c.ac=("https:"===a.c.protocol?"z":"js")+".moatads.com";a.c.f=window!=window.parent;var m=a.d.g(window.parent);a.c.s=a.c.f&&!m;a.c.ad=a.b.w();a.c.a=m?!1:!a.d.g(window.top);a.c.c=a.c.a?window.top:a.c.s?window.parent:window;a.b.ac().isInApp&&(a.c.a=a.b.aj()||a.b.ah());a.c.b=a.c.c.document.referrer||"";try{a.c.ae=a.c.c.history&&a.c.c.history.length}catch(p){}try{if(!a.c.a){var m=
window,h;for(h=0;20>h&&m!=window.top;h++)m=m.parent;a.c.af=h}}catch(p){}a.c.ag=function(){var b=a.c.c;if(!b)return!1;try{var d=b.document&&b.document.body,e=b.document&&b.document.documentElement}catch(r){}try{b.screen&&(a.c.ah=b.screen.availWidth,a.c.ai=b.screen.availHeight,a.c.aj=b.screen.width,a.c.ak=b.screen.height)}catch(r){a.c.ah=a.c.ah||0,a.c.ai=a.c.ai||0,a.c.aj=a.c.aj||0,a.c.ak=a.c.ak||0}var c=a.c.al(b);a.c.am=c.width;a.c.an=c.height;try{a.c.ao=b.outerWidth||b.document&&b.document.body&&b.document.body.offsetWidth||
0,a.c.ap=b.outerHeight||b.document&&b.document.body&&b.document.body.offsetHeight||0}catch(r){a.c.ao=0,a.c.ap=0}d&&e&&(a.c.aq=t.max(d.scrollHeight,d.offsetHeight,e.clientHeight,e.scrollHeight,e.offsetHeight),a.c.ar=d.scrollTop||e.scrollTop||b.pageYOffset||0)};a.c.al=function(a){var b,d,c,r=0,g=0;try{(b=a.document,d=b.documentElement,c=b.body,"undefined"!==typeof a.innerWidth)?(r=a.innerWidth,g=a.innerHeight):"CSS1Compat"===b.compatMode&&5!==b.documentMode||!c||"undefined"===typeof c.clientWidth?d&&
"undefined"!==typeof d.clientWidth&&(r=d.clientWidth,g=d.clientHeight):(r=c.clientWidth,g=c.clientHeight)}catch(e){}return{width:r,height:g,left:0,right:r,top:0,bottom:g}};a.c.ag();a.c.as=function(){if(y)for(var a in y)if(y.hasOwnProperty(a))return!0;return!1};a.c.at=function(b){var d=!0;a.b.forEach(b&&b.parentNode&&b.parentNode.childNodes,function(b){if(a.b.m(["DIV","IFRAME","A","EMBED","OBJECT"],b.nodeName))return d=!1});return d};a.c.au=function(){for(var a in y)if(y.hasOwnProperty(a)){var b=y[a];
if(b&&b.aa&&b.aa[MOATALREADYFOUND])return!0}return!1};a.c.av=function(){return a.c.a};a.c.aw=function(){return a.c.y||a.c.w&&a.c.w()};a.c.ax=function(){return a.c.aa&&a.c.aa()};a.c.ay=function(b){var d=!1;a.g&&a.g.a()?d=!0:a.h&&a.h.a&&(b&&b.periscopeManager?b.periscopeManager.measurable&&(d=!0):d=!0);return d};a.c.az=function(b){return b?a.c.av()||a.c.aw()||a.c.ay(b)||a.c.ax()?!0:!1:!1};a.c.e=new a.c.c.Image;a.c.h=function(){if("undefined"!==typeof a.c.c["Moat#EVA"])return!0;try{if("undefined"!==
typeof a.c.c.eval&&(a.c.c.eval("(function(win){ win['Moat#EVA'] = true; })(window)"),"undefined"!==typeof a.c.c["Moat#EVA"]))return!0}catch(b){}return!1}})(v);(function(a){function e(a,d,e){function h(a,b){for(var c in a)a.hasOwnProperty(c)&&b.call(null,a[c],c)}function p(a){var b=[];h(a,function(a,d){b.push(d)});return b}a=d[a];a&&a.xa.sode||(a.xa.sode=function(){this.desw={};this.xfgf=[];this.publishing_=!1;this.xkcd={};this.edws=[]},a.xa.sode.prototype.uxin=function(){var a=function(a){a=e.max(4,
a);return((1+e.random())*e.pow(16,a)|0).toString(16).substring(0,a)};return function(b){return a(4)+"-"+a(4)+"-"+a(4)+"-"+a(4)}}(),a.xa.sode.prototype.xsza=function(a){this.desw[a]||(this.desw[a]={});return this.desw[a]},a.xa.sode.prototype.esgf=function(a,b){this.publishing_?this.xfgf.push(arguments):this.zaxs.apply(this,arguments)},a.xa.sode.prototype.kswa=function(a,b){for(var c=this.xkcd[a]||[],d=c&&c.length,g=0;g<d;g++)if(c[g]===b)return!1;c.push(b);c.sort(function(a,c){return a-c});this.xkcd[a]=
c},a.xa.sode.prototype.aksw=function(a,b){if(!this.xkcd[a])return!1;for(var c=this.xkcd[a],d=-1,g=c&&c.length,e=0;e<g;e++)if(c[e]===b){d=e;break}-1!=d&&c.splice(d,1);this.xkcd[a]=c},a.xa.sode.prototype._getEventPriorities_=function(a){return this.xkcd[a]||[]},a.xa.sode.prototype.azsx=function(a,b,c){c=c||{};var d=c.id||this.uxin(),g;g=c.priority;g=!isNaN(g)&&isFinite(g)?parseInt(g,10):10;for(var e=this.xsza(a),f=0;e[d]&&!c.id&&10>f;)f++,d=this.uxin();e[g]||(e[g]={});this.kswa(a,g);c.priority=g;e[g][d]=
{cb:b,options:c};return d},a.xa.sode.prototype.zaxs=function(a,b){if(!this.desw[a])return!1;this.publishing_=!0;for(var c=this.edws.slice.call(arguments,1),d=this._getEventPriorities_(a),g=0,e=d.length;g<e;g++){var f=d[g],k;for(k in this.desw[a][f]){var h=this.desw[a][f][k];if(h){var m;m=h.options.includeId?[k].concat(c):c;if(!h.options.condition||h.options.condition&&h.options.condition.apply(null,m))h.options.once&&this.sxaz(a,{id:k,priority:h.options.priority}),h.cb.apply(null,m)}}}this.publishing_=
!1;g=0;for(c=this.xfgf.length;g<c;g++)this.zaxs.apply(this,this.xfgf.pop())},a.xa.sode.prototype.swaq=function(a,b,c){var d=!1;if(this.desw[a]&&this.desw[a][c])try{delete this.desw[a][c][b],d=!0}catch(g){}0===p(this.desw[a][c]).length&&this.aksw(a,c);return d},a.xa.sode.prototype.sxaz=function(a,b){if(!b||"object"!=typeof b||!this.desw[a])return!1;if(b.id&&void 0!==b.priority)return this.swaq(a,b.id,b.priority);if(b.id||b.callback)for(var c=this._getEventPriorities_(a),d=0,g=c.length;d<g;d++){var e=
c[d];if(b.id&&b.callback){if(this.desw[a][e][b.id]&&this.desw[a][e][b.id].cb==b.callback)return this.swaq(a,b.id,e)}else if(b.id){if(this.desw[a][e][b.id])return this.swaq(a,b.id,e)}else for(var f in this.desw[a][e])if(this.desw[a][e][f]&&this.desw[a][e][f].cb==b.callback)return this.swaq(a,f,e)}return!1},a.xa.sode.prototype.ugin=function(a){if("string"===typeof a)if(this.desw[a])delete this.desw[a];else return!1;else this.desw={};return!0})}a.i={};a.i.a=function(b){b.xa.sode||(b.xb==window?e(a.c.j,
window,t):a.b.cc(e,"'"+a.c.j+"',window, Math",b.xb));a.i.b=new b.xa.sode}})(v);(function(a){function e(a,d){function e(a){var b=l.xb.Math.pow,d=l.xb.Math.random;a=(0,l.xb.Math.max)(4,a);return((1+d())*b(16,a)|0).toString(16).substring(0,a)}function h(a){return function(b){return a(b)}}function p(a,b){if(!a||"string"!==typeof b||!a[b]||a==window)return!1;if("string"===typeof a.nodeName&&("OBJECT"===a.nodeName||"EMBED"===a.nodeName)){var d=document&&document.body&&document.body[b];if(d&&d!==a[b])return d}return!1}
d[a]=d[a]||{zs:!1,zr:0,yf:{},h:0,m:0,i:{},xa:{},xb:d,xc:{}};var l=d[a],q={};l.xc.esde=function(a){window&&window.clearTimeout&&window.clearTimeout(a)};l.xc.ynds=function(a,b,d,e){var f,k=h(d),m;a.addEventListener?(d="addEventListener",f=""):(d="attachEvent",f="on");if(m=p(a,d))try{m.call(a,f+b,k,!1)}catch(l){a[d](f+b,k,!1)}else if(a&&d&&a[d])try{a[d](f+b,k,!1)}catch(l){}!1!==e&&(q[b+e]=k)};l.xc.engn=function(a,b,d,e){var f,k=b+e,h;if(!a)return delete q[k],!1;d=!1!==e?q[k]:d;a.removeEventListener?
(e="removeEventListener",f=""):(e="detachEvent",f="on");if(h=p(a,e))try{h.call(a,f+b,d,!1)}catch(m){a[e](f+b,d,!1)}else try{a[e](f+b,d,!1)}catch(m){}delete q[k]};l.xc.exde=function(a,b){a=h(a);var d;window&&window.setTimeout&&(d=window.setTimeout(a,b));return d};l.xc.exae=function(a,b,d){return function(){b.apply(d||null,a.concat(a.slice.call(arguments)))}};l.xc.uxin=function(){return e(4)+"-"+e(4)+"-"+e(4)+"-"+e(4)};l.xc.twer=function(a,b){l&&(l.yf||(l.yf={}),l&&l.yf&&(l.yf[b]?l.yf[b].push(a):l.yf[b]=
[a]))}}a.j={};a.j.a=function(b){var d=a.j.b(b),e=!1;d||(d=a.j.c(b),e=!0);window[a.c.j]=d;a.i.a(d);e&&(d.swde=new d.xa.sode);a.i.b.azsx("adKilled",a.j.d);a.i.b.azsx("allLocalAdsKilled",a.j.e,{once:!0});return d};a.j.e=function(){a.i.b.sxaz("adKilled",{callback:a.j.d});a.j.f(w)};a.j.d=function(b){if(w){try{var d=w.yf[a.c.l.a];if(d){var e=a.b.indexOf(d,b.yg);-1<e&&d.splice(e,1)}}catch(h){}a.j.f(w)}};a.j.g=function(b,d){var e=a.j.b(a.c.c);e&&e.xc.twer(b,d)};a.j.f=function(b){var d=!1,e=!1,h=0;try{b.yf[a.c.l.a]&&
(e=0===b.yf[a.c.l.a].length),a.b.forEach(b.yf,function(a){0<a.length&&h++}),0===h&&(d=!0)}catch(p){}e&&b.swde.esgf("allAdsInWindowKilled",a.c.l.a);d&&(a.i.b.sxaz("adKilled",{callback:a.j.d}),a.i.b.sxaz("allLocalAdsKilled",{callback:a.j.e}),b.swde.esgf("allAdsKilled"))};a.j.c=function(b){b==window?e(a.c.j,window):a.b.cc(e,"'"+a.c.j+"',window",b);return a.j.b(b)};a.j.b=function(b){try{return b=b||a.c.c,b[a.c.j]}catch(d){return null}};a.j.h=function(b){var d=a.j.b();d&&(d.i[b]=!0)}})(v);var w=v.j.a(v.c.c);
(function(a){function e(a,d,e){var h=d[a];h&&h.xa.txae||(h.xa.txae=function(a,b){this.sxdc=h.xc.uxin();this.cdxs=a;this.xscd={};this.swde=b;var d=this,c=this.swde.azsx("allAdsInWindowKilled",function(a){h.dcsx.engn({listenerName:"unloadFn"+a});h.dcsx.engn({listenerName:"beforeunloadFn"+a})});this.swde.azsx("allAdsKilled",function(){d.swde.sxaz("allAdsInWindowKilled",{id:c});h.dcsx&&(h.dcsx.aqsw(),h.zs=!1,h.xz=!1,h.dcsx=!1)},{once:!0})},h.xa.txae.prototype.wsed=function(a,b,d,c,e){this.xscd[c]||(this.xscd[c]=
{});this.xscd[c].evt=b;this.xscd[c].target=a;this.xscd[c].periodic=!0;var g;g=h.xc.exae([this],function(m,f){h.xc.engn(a,b,null,c);if(m.xscd[c]){m.xscd[c].tid=h.xc.exde(function(){h.xc.ynds(a,b,g,c)},e);try{m.swde.zaxs(d,f)}catch(k){}}});h.xc.ynds(a,b,g,c)},h.xa.txae.prototype.wsqa=function(a){this.xscd[a]&&(h.xc.esde(this.xscd[a].tid),h.xc.engn(this.xscd[a].target,this.xscd[a].evt,null,a),delete this.xscd[a])},h.xa.txae.prototype.qaws=function(){this.wsed(this.cdxs,"scroll","scroll","globalScrollevent"+
this.sxdc,1E3)},h.xa.txae.prototype.aqsw=function(){for(var a in this.xscd)this.engn({listenerName:a})},h.xa.txae.prototype.ynds=function(a,b,d,c){if(!this.xscd[c]){this.xscd[c]={};this.xscd[c].evt=b;this.xscd[c].target=a;var e;e=h.xc.exae([this],function(a,b){a.xscd[c]&&a.swde.zaxs(d,b)});h.xc.ynds(a,b,e,c)}},h.xa.txae.prototype.engn=function(a){function b(a,c){a.xscd[c].periodic?a.wsqa(c):(h.xc.engn(a.xscd[c].target,a.xscd[c].evt,null,c),delete a.xscd[c])}var d=a.target&&a.evt,c=a.target&&!a.evt,
e=a.all;if(a.listenerName)this.xscd[a.listenerName]&&b(this,a.listenerName);else if(d)for(var g in this.xscd)(d=this.xscd[g])&&d.evt==a.evt&&d.target==a.target&&b(this,g);else if(c)for(g in this.xscd)(d=this.xscd[g])&&d.target==a.target&&b(this,g);else if(e)for(g in this.xscd)(d=this.xscd[g])&&b(this,g)})}a.k={};a.k.a=function(b){b&&(b.xa.txae||(b.xb==window?e(a.c.j,window,t):a.b.cc(e,"'"+a.c.j+"',window, Math",b.xb)),b.zs||(b.dcsx=new b.xa.txae(a.c.c,b.swde),b.zs=!0))};a.i.b.azsx("modulesReady",
a.k.a,{once:!0});a.i.b.azsx("startAdTracking",function(b){w&&w.zs&&!w.xz&&(w.dcsx?(w.xz=!0,w.dcsx.qaws()):a.k.a(w),a.focus.setFocusListeners())})})(v);(function(a){function e(a){return function(){var b=!1;return function(e){try{return a&&a.apply?a.apply(null,arguments):a(e)}catch(g){if(!b){b=!0;var p=(new x).getTime();window["Moat#ETS"]||(window["Moat#ETS"]=p);window["Moat#EMC"]||(window["Moat#EMC"]=0);var l=36E5<=p-window["Moat#ETS"],q="";try{q=a.toString()}catch(z){q="failed"}q=g.name+" in closure (cb): "+
g.message+", stack="+g.stack+", \ncb="+q+"\n";if(!l&&10>window["Moat#EMC"]){window["Moat#EMC"]++;try{var c="//v4.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("REDDITADZERK1")+"&ac=1&k="+escape(q)+"&ar="+escape("e7548e3-clean")+"&j="+escape(document.referrer)+"&cs="+(new x).getTime(),r=new Image(1,1);r.src=c}catch(z){}}else if(l){window["Moat#EMC"]=1;window["Moat#ETS"]=p;try{c="//v4.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("REDDITADZERK1")+"&ac=1&k="+
escape(q)+"&ar="+escape("e7548e3-clean")+"&j="+escape(document.referrer)+"&cs="+(new x).getTime(),r=new Image(1,1),r.src=c}catch(z){}}}}}}()}a.f={};var b={};a.f.b=b;a.f.c=function(b,e){if(!b||"string"!==typeof e||!b[e]||b==window)return!1;if("string"===typeof b.nodeName&&("OBJECT"===b.nodeName||"EMBED"===b.nodeName)){var h=a&&a.l&&a.l[e];if(h&&h!==b[e])return h}return!1};a.f.d=function(d,m,h,p){var l,q=e(h),c;d.addEventListener?(h="addEventListener",l=""):(h="attachEvent",l="on");if(c=a.f.c(d,h))try{c.call(d,
l+m,q,!1)}catch(r){d[h](l+m,q,!1)}else if(d&&h&&d[h])try{d[h](l+m,q,!1)}catch(r){}!1!==p&&(b[m+p]=q)};a.f.e=function(d,e,h,p){var l,q=e+p,c;if(!d)return delete b[q],!1;h=!1!==p?b[q]:h;d.removeEventListener?(p="removeEventListener",l=""):(p="detachEvent",l="on");if(c=a.f.c(d,p))try{c.call(d,l+e,h,!1)}catch(r){d[p](l+e,h,!1)}else try{d[p](l+e,h,!1)}catch(r){}delete b[q]};a.f.f=function(a,b){a=e(a);var h;window&&window.setInterval&&(h=window.setInterval(a,b),B.push(h));return h};a.f.g=function(a,b){a=
e(a);var h;window&&window.setTimeout&&(h=window.setTimeout(a,b),A.push(h));return h};a.f.a=function(b,m,h,p){if(!p)return!1;p+="";u[p]&&a.b.ca(u[p].tid);u[p]={};u[p].callback=e(b);u[p].params=m;u[p].interval=h;u[p].tid=a.f.g(a.f.h(p),h);callbacks=null};a.f.h=function(b){return function(){if(!u||!u[b])return!1;var e=u[b].callback(u[b].params);if("boolean"===typeof e&&!1===e)return a.b.ca(u[b].tid),u[b]=!1;u[b].tid=a.f.g(a.f.h(b),u[b].interval);time=b=null}};a.f.i=function(){return u};a.f.j=function(b,
e,h,p){var l=0,q=function(){l+=1;!0!==b()&&(l<e?a.f.g(q,h):"function"===typeof p&&p())};q()};a.f.k=e})(v);(function(a){function e(b){a.focus.pageIsPrerendered()||a.f.e(document,c,e,"pr")}function b(a){"undefined"==typeof p&&(p=a)}a.focus={};var d=navigator.userAgent,d=-1<d.indexOf("Safari")&&-1==d.indexOf("Chrome")&&-1==d.indexOf("Chromium")&&!a.b.w(),m=a.b.l()&&!a.b.w(),h="undefined"!==typeof document.hasFocus,p,l={visible:0,hidden:1,prerender:2},q,c,r,g;"undefined"!==typeof document.hidden?(q="hidden",
c="visibilitychange"):"undefined"!==typeof document.mozHidden?(q="mozHidden",c="mozvisibilitychange"):"undefined"!==typeof document.msHidden?(q="msHidden",c="msvisibilitychange"):"undefined"!==typeof document.webkitHidden&&(q="webkitHidden",c="webkitvisibilitychange");for(var z=["v","mozV","msV","webkitV"],f=0;f<z.length;f++){var k=z[f]+"isibilityState";if("undefined"!==typeof document[k]){r=k;break}}g="undefined"!==typeof q;var n,t;"undefined"!==typeof window.requestAnimationFrame?n="requestAnimationFrame":
"undefined"!==typeof window.webkitRequestAnimationFrame&&(n="webkitRequestAnimationFrame");t=d&&"string"==typeof n&&!g;var u=(new x).getTime();t&&function C(){u=(new x).getTime();window[n](C)}();a.focus.getFocusMethod=function(){return p};a.focus.visibilitychange=c;a.focus.setFocusListeners=function(){};a.focus.getQueryString=function(a){a={};a.em=p;v&&(a.eo=1);"undefined"!=typeof r&&(a.en=l[document[r]]);return a};a.focus.supportsPageVisAPI=function(){return g};a.focus.checkFocus=function(){if(a.focus.supportsPageVisAPI())return b(0),
!document[q];if(t)return b(1),100>(new x).getTime()-u;if(m&&h)return b(2),document.hasFocus();b(3);return!0};_lastFocusState=!1;a.focus.pageIsVisible=function(){var b=a.focus.checkFocus();if(_lastFocusState!=b&&w&&w.swde)try{w.swde.zaxs("focusStateChange",b)}catch(c){}return _lastFocusState=b};a.focus.pageIsPrerendered=function(){return"undefined"!==typeof r?"prerender"==document[r]:!1};a.focus.pageIsVisible();a.focus.pageIsPrerendered()&&(a.f.d(document,c,e,"pr"),a.i.b.azsx("allLocalAdsKilled",function(){a.f.e(document,
c,e,"pr")},{once:!0}));var v=a.focus.pageIsPrerendered()})(v);(function(a){function e(b,e){if(!b)return!1;var g,h;"number"==typeof b.zr?(g=b.aa,h=b._calcVideoBasedOnContainer):g=b;h=h?new a.m.j(g.parentNode,e):new a.m.j(g,e);g=h.height;var f=h.width,k=h.calcArea();if(0===k)return{area:k,percv:0};var n=d(h),m=n.visibleRect.calcArea(),l=m/k,p;a:{var q=n.cumulRect,t=n.cumulRect.getViewportRect();if(0>q.top&&0<q.bottom)p=-q.top;else if(0<=q.top&&q.top<=t.height)p=0;else{p={yMin:-1,yMax:-1};break a}if(0<=
q.bottom&&q.bottom<=t.height)q=q.height;else if(q.bottom>t.height&&q.top<t.height)q=q.height-(q.bottom-t.height);else{p={yMin:-1,yMax:-1};break a}p={yMin:p,yMax:q}}return{area:k,visibleArea:m,visibleRect:n.visibleRect,cumulRect:n.cumulRect,percv:l,yMinMax:p,elGeo:{elHeight:g,elWidth:f,foldTop:n.cumulRect.top,totalArea:n.parentArea},rect:h.rect}}function b(a,b){for(var d=[],e=0;e<b.length;e++)d.push(a(b[e]));return d}function d(c){var d,e=a.b.bx(c.el,c.win),e=b(function(b){return new a.m.j(b)},e);
e.unshift(c);var h=e.length;c=new a.m.j(c.el,a.c.c);for(var f=0;f<h;f++){var k=e[f];0===f?d=k:(d.changeReferenceFrame(k),c.changeReferenceFrame(k));k=k.getViewportRect(f<h-1?e[f+1]:!1);d=a.m.l(d,k)}return{visibleRect:d,cumulRect:c,parentArea:e[e.length-1].calcArea()}}function m(a,b,d,e){a=t.max(a,d);b=t.min(b,e);return b>a?[a,b]:[0,0]}function h(b,d,e,h){var f=[],k;for(k in b){var n=b[k],n=a.b.bt(n[0],n[1],d),m;if(m=n&&n!==e&&n[DOM_NODE_KEY]!==h)n=(n=a.b.as(n))&&(1>=n.width||1>=n.height)?!0:!1,m=
!1===n;m&&f.push(k)}return f}function p(a){var b=.01*a.width,d=.01*a.height;return{tl:[a.left+b,a.top+d],m:[a.left+(a.right-a.left)/2,a.top+(a.bottom-a.top)/2],br:[a.right-b,a.bottom-d]}}function l(c,d){var e={corners:[],addCorner:function(b){var c=this;a.b.forEach(b,function(b){-1===a.b.indexOf(c.corners,b)&&c.corners.push(b)})}},m=a.d.e(c),m=b(function(b){var d=new a.m.j(c),e=new a.m.j(b);d.changeReferenceFrame(e);return{rect:d,frame:b,doc:b.ownerDocument}},m);m.unshift({rect:new a.m.j(c),frame:c,
doc:c.ownerDocument});a.b.forEach(m,function(a){var b=p(a.rect);e.addCorner(h(b,a.doc,a.frame,d))});return e.corners}a.m={};var q=a.c.a;a.m.a=.5;a.m.b=.3;a.m.c=236425;a.m.d=.98;a.m.e=void 0;a.m.f=function(b,d){d=d||!1;return function(g,h){var f=g.ao.skin?a.m.g(g,h):e(g,h);f.isVisible=d?f.percv>b:f.percv>=b;f.elGeo&&(f.elGeo.threshold=b);return f}};a.m.g=function(b,d){if(1==b.ao.skin){var g={},h=a.c.c.scrollY||a.c.c.document.documentElement.scrollTop;if("width"==a.n.a&&a.n.b<=b.adContent&&45<h||!a.focus.pageIsVisible())return g.isVisible=
!1,g.isFullyVisible=!1,g.percv=0,g;g.isVisible=!0;g.isFullyVisible=!0;g.isDentsuVisible=!0;g.percv=1;return g}var g=e(b,d),h=a.m.h(g,b),f=a.m.d;g.isVisible=g.percv>=h;g.isFullyVisible=g.percv>=f;g.elGeo&&(g.elGeo.threshold=h);b.videoIsFullscreen&&0<g.percv&&(g.isVisible=!0);.8<=g.percv&&(g.isDentsuVisible=!0);a.m.e?g.percv>a.m.e&&(a.m.e=g.percv):a.m.e=g.percv;return g};a.m.h=function(b,d){return b.area>=a.m.c?(d.viewstats||(d.viewstats={}),d.viewstats.isBigAd=!0,a.m.b):a.m.a};a.m.i=function(){return q};
a.m.k=a.c.al;a.m.j=function(b,d,e,h){try{this.rect=e||b.getBoundingClientRect&&b.getBoundingClientRect()||{}}catch(k){this.rect=e||b&&{top:b.offsetTop,left:b.offsetLeft,width:b.offsetWidth,height:b.offsetHeight,bottom:b.offsetTop+b.offsetHeight,right:b.offsetLeft+b.offsetWidth}||{}}e="left right top bottom width height".split(" ");for(h=0;h<e.length;h++){var f=e[h];this[f]=this.rect[f]}b&&b.adjustForClip&&(e=a.b.br(b.style.clip))&&(this.left+=e.left,this.right=this.left+e.right,this.top+=e.top,this.bottom=
this.top+e.bottom);b&&b.CLIPCHECKINGTARGET&&(e=a.b.br(b.CLIPCHECKINGTARGET.style.clip))&&(this.right=this.left+e.right,this.left+=e.left,this.bottom=this.top+e.bottom,this.top+=e.top);this.width=this.right-this.left;this.height=this.bottom-this.top;this.el=b;this.win=d||b&&a.b.r(b);this.changeReferenceFrame=function(a){this.left+=a.left;this.right+=a.left;this.top+=a.top;this.bottom+=a.top};this.calcArea=function(){return(this.right-this.left)*(this.bottom-this.top)};this.getViewportRect=function(b){var c=
a.c.al(this.win);b&&(b.width<c.width&&(c.width=b.width,c.right=c.left+c.width),b.height<c.height&&(c.height=b.height,c.bottom=c.top+c.height));return c}};a.m.m=function(a,b,d){return{left:Number(b)+Number(a.left),right:Number(b)+Number(a.right),top:Number(d)+Number(a.top),bottom:Number(d)+Number(a.bottom)}};a.m.m=function(a,b,d){return{left:Number(b)+Number(a.left),right:Number(b)+Number(a.right),top:Number(d)+Number(a.top),bottom:Number(d)+Number(a.bottom)}};a.m.l=function(b,d){var e=m(b.left,b.right,
d.left,d.right),h=m(b.top,b.bottom,d.top,d.bottom);return new a.m.j(void 0,void 0,{left:e[0],right:e[1],top:h[0],bottom:h[1]})};a.m.n=function(a,b){b||(b=window);try{var d=b.document.documentElement,e=b.document.body;return"left"===a?b.pageXOffset||d&&d.scrollLeft||e&&e.scrollLeft:b.pageYOffset||d&&d.scrollTop||e&&e.scrollTop}catch(f){return!1}};a.m.o=e;a.m.p=function(b){var d=b.aa;b=b.zr;if(d){if(a.c.s)d=l(d,b);else var e=new a.m.j(d),e=p(e),d=h(e,a.c.c.document,d,b);return{half:1<d.length?!0:!1,
full:3===d.length?!0:!1}}}})(v);(function(a){a.o={};a.o.a="1.2";a.o.prefix="MSFAPI";a.o.b={};a.o.c={};a.o.d=t.floor(t.random()*t.pow(10,12));a.o.e=!1;a.o.f=/([a-z]+)#([a-z0-9.-]+)#([0-9]+)#([a-z]+)#([0-9]+)#(.+)/i;a.o.g=/@([a-z0-9]+)@@(.*)/i;a.o.h=function(e){if(e&&(e["Moat#PML#"+a.o.a]?a.o.i=e["Moat#PML#"+a.o.a].id:(e["Moat#PML#"+a.o.a]={id:t.floor(t.random()*t.pow(10,12))},a.o.i=e["Moat#PML#"+a.o.a].id,w.dcsx.ynds(e,"message","message-"+a.o.i,"ME-"+a.o.a)),!a.o.e)){a.o.e=!0;var b=w.swde.azsx("message-"+
a.o.i,a.o.j);a.i.b.azsx("allLocalAdsKilled",function(){w.swde.sxaz("message-"+a.o.i,{id:b})},{once:!0})}};a.o.k=function(e){e&&e&&e["Moat#PML#"+a.o.a]&&(e["Moat#PML#"+a.o.a]=!1,a.f.e(e,"message",a.o.j))};a.o.l=function(e){return a.o.prefix+"#"+e+"#"};a.o.m=function(e){var b=e.match(a.o.f);e=!1;b&&7==b.length&&(e={prefix:b[1],version:b[2],uid:b[3],type:b[4],request:b[5],data:b[6]},(b=e.data.match(a.o.g))&&3==b.length&&(e.cmd=b[1],e.arg=b[2]));return e};a.o.j=function(e){if(!(e&&e.origin&&e.data&&"string"===
typeof e.data))return!1;if((msgData=a.o.m(e.data))&&(!msgData||msgData.uid!=a.o.d.toString())&&msgData.version==a.o.a&&(e.msgData=msgData,msgData.request in a.o.c&&(e.triggerCallback=function(){a.o.c[msgData.request]&&(a.o.c[msgData.request](e),a.o.c[msgData.request]=null,delete a.o.c[msgData.request])}),a.o.b[msgData.type]))for(var b=0,d=a.o.b[msgData.type].length;b<d;b++)a.o.b[msgData.type][b](e)};a.o.n=function(e,b){a.o.b[e]=[b]};a.o.o=function(e,b,d,m){"object"==typeof b&&(b=a.b.aq(b));m=m||t.floor(1E10*
t.random());"function"==typeof d&&(a.o.c[m]=d);e=a.o.l(a.o.a)+a.o.d+"#"+e+"#"+m+"#"+b;return{request:m,msg:e}};a.o.p=function(e,b,d,m,h){"object"==typeof d&&(d=a.b.aq(d));return a.o.o(e,"@"+b+"@@"+d,m,h)};a.o.q=function(e,b,d){try{if(!e||!e||!e.source)return!1;e.source.postMessage(a.o.o(e.msgData.type,b,d,e.msgData.request).msg,"*")}catch(m){return!1}return!0};a.o.r=function(e,b,d){try{var m=a.d.h(b||window.top);if(!m)return a.f.g(function(){a.o.r(e,b,d)},200);for(var h=0;h<m.length;h++)d&&m[h]==
window||m[h].postMessage(e,"*")}catch(p){}};a.i.b.azsx("modulesReady",a.b.bw([window],a.o.h),{once:!0})})(v);(function(a){a.p={};a.p.a={};a.p.a.a="CF";a.p.a.b="CNF";a.p.a.c="CNS";a.p.b={};a.p.b.a=!1;a.p.b.b=[];a.p.c={};a.p.d={};var e=!1;a.p.b.c=function(){var b=a.p.e();a.p.b.a||a.c.a||(b=a.o.p("moatframe","check",b,function(b){if((b=a.b.ar(b.msgData.data))&&b.available&&!a.p.b.a){a.c.y=!0;a.p.b.a=!0;b="MoatFrame#perc#"+(new x).getTime();var e="MoatFrame#geom#"+(new x).getTime();a.f.a(a.p.b.d,null,
200,e);a.p.b.b.push(b);a.p.b.b.push(e)}}),a.o.r(b.msg,!1,!0))};a.p.f=function(){a.o.n("moatframe",a.p.g);a.o.r(a.o.o("moatframe","ping").msg,!1,!0)};a.p.h=function(b){return"undefined"!==typeof b&&a.p.d&&a.p.d[b]?(a.p.d[b]=null,!0):!1};a.p.e=function(){var b=a.c.am,d=a.c.an;return b&&d?{width:b,height:d}:!1};a.p.i=function(){return a.c.a};a.p.j=function(b){var d=!1;a.b.forEach(a.p.a,function(a){if(a==b)return d=!0,!1});return d};a.p.g=function(b){var d=b.msgData.cmd||b.msgData.data;if(d)if(b.triggerCallback)b.triggerCallback(b);
else if(a.p.c[d])a.p.c[d](b);else a.p.j(d)||a.o.q(b,a.p.a.b)};a.p.k=function(b,d){if(!b||!d)return!1;for(var e=a.d.f(window).pop(),h=a.d.j(b,10),p=!1,l=!1,q=null,c=null,r,g=h.length-1;0<=g;g--)if(h[g]==e&&(p=!0),p&&!a.d.i(h[g])){c=h[g];break}p&&c&&((q=c&&c.parent&&c.parent.document)&&(r=a.d.c(q,c)),r&&(e=r.offsetWidth,h=r.offsetHeight,e==d.width&&h==d.height?l=!0:(e*=h,h=d.width*d.height,l=.98<=t.min(e,h)/t.max(e,h))));return{isNested:l,iframe:r,iframeParentDoc:q}};a.p.l=function(b){return b&&b.parent&&
a.d.c(b.parent.document,b)};a.p.m=function(b){(b="undefined"!==typeof b&&a.p.d&&a.p.d[b])&&"boolean"==typeof b.isWithinReach&&(b.isNested&&!b.iframeParentDoc&&(b.isWithinReach=!1),b.isNested||b.win&&!a.d.g(b.win)||(b.isWithinReach=!1));return b};a.p.n=function(b,d,e,h){var p,l,q={isNested:!1,iframe:null,iframeParentDoc:null};if((p=a.p.m(e))&&p.isWithinReach)return!0;l=a.d.l(b,d,!0);p&&"undefined"==typeof p.isWithinReach?p.isWithinReach=l:(l?d=a.p.l(d):(q=a.p.k(d,h),(d=q.iframe)&&(l=!0)),p={dimensions:h,
iframe:d,iframeParentDoc:q.iframeParentDoc,isNested:q.isNested,isWithinReach:l,win:b},a.p.d[e]=p);return p.isWithinReach};a.p.b.d=function(){if(!e){e=!0;var b=a.o.o("moatframe","geom",function(b){e=!1;a.p.j(b.msgData.data)||(a.p.b.e=a.b.ar(b.msgData.data))});a.o.r(b.msg,!1,!0)}};a.p.c.ping=function(b){!a.c.a&&a.c.as()&&a.p.b.c()};a.p.c.check=function(b){var d={},e=b.msgData.arg&&a.b.ar(b.msgData.arg);a.p.n(window,b.source,b.msgData.uid,e)&&a.p.i()?d.available=!0:d.available=!1;a.o.q(b,d)};a.p.c.geom=
function(b){if(a.p.n(window,b.source,b.msgData.uid)&&a.p.i()){var d=a.p.d&&a.p.d[b.msgData.uid]&&a.p.d[b.msgData.uid].iframe;if(d&&(d=a.m.o(d))&&d.visibleRect&&d.rect){a.o.q(b,{w:d.cumulRect.width,h:d.cumulRect.height,vl:d.visibleRect.left,vt:d.visibleRect.top,vr:d.visibleRect.right,vb:d.visibleRect.bottom,el:d.cumulRect.left,et:d.cumulRect.top,er:d.cumulRect.right,eb:d.cumulRect.bottom});return}a.o.q(b,a.p.a.a)}else a.o.q(b,a.p.a.c)}})(v);v.i.b.zaxs("modulesReady",w);v.b.w();var D=v.c.c;if(v.b.ak()||
v.b.al())return!1;v.b.ac().isInApp||v.p.f()})(Date,Math)}catch(x){var ct=(new Date).getTime();window["Moat#ETS"]||(window["Moat#ETS"]=ct);window["Moat#EMC"]||(window["Moat#EMC"]=0);var et=ct-window["Moat#ETS"],hourElapsed=36E5<=et,msg=x.name+" in closure (global): "+x.message+", stack="+x.stack;if(!hourElapsed&&10>window["Moat#EMC"]){window["Moat#EMC"]++;try{var pixelDomain="v4.moatads.com",pxSrc="//"+pixelDomain+"/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("undefined"===typeof AD_VIEW_HASH?
"REDDITADZERK1":AD_VIEW_HASH)+"&ac=1&k="+escape(msg)+"&ar="+escape("e7548e3-clean")+"&j="+escape(document.referrer)+"&cs="+(new Date).getTime(),px=new Image(1,1);px.src=pxSrc}catch(t){}}else if(hourElapsed){window["Moat#EMC"]=1;window["Moat#ETS"]=ct;try{pixelDomain="v4.moatads.com",pxSrc="//"+pixelDomain+"/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("undefined"===typeof AD_VIEW_HASH?"REDDITADZERK1":AD_VIEW_HASH)+"&ac=1&k="+escape(msg)+"&ar="+escape("e7548e3-clean")+"&j="+escape(document.referrer)+
"&cs="+(new Date).getTime(),px=new Image(1,1),px.src=pxSrc}catch(t){}}};
